lib/miniproxy/remote.rb, spec/lib/miniproxy/remote_spec.rb
Make it as easy as possible to stub requests by adding sample code to the "unmocked request" error message.
=> Add stubbing instructions to error message

.travis.yml, README.md, miniproxy.gemspec, spec/integration/stub_requests_spec.rb, spec/support/capybara_driver.rb
They aren't perfect, but will offer a decent enough safety net while we're making changes separately from the main app.
I'd originally used Chrome, but got stung by a nasty gotcha where the `--headless` flag causes other arguments to be completely ignored, so Miniproxy wasn't working as expected. This is probably going to cause issues in TC. So we might want to document/investigate this point further.
Also the warning output is not being captured by rspec for some reason, so that also needs investigation. Those specs are marked as pending.
=> Add integration specs

README.md, lib/miniproxy/server.rb, spec/integration/ignore_all_requests_spec.rb
Often lingering requests will hit the proxy between spec examples, causing unmocked request warning noise. Add a method to ignore all requests between spec examples.
=> Add method to ignore all requests between specs

.rspec, spec/spec_helper.rb
Otherwise, DRb server will keep running on the background as a zombie process.
=> Stop DRb server after the test suite

lib/miniproxy/version.rb, miniproxy.gemspec
This PR aims to add the `version.rb` file pattern, removing the hardcoded version on its gemspec. Also, bumping MiniProxy to its `0.0.1` version.
This file comes by default when creating a gem using `bundler`'s `gem` generator: `bundle gem miniproxy`.
=> Create version file

lib/miniproxy/fake_ssl_server.rb
On MacOS this was causing timeouts and was slowing everything down
for up to two minutes. It's not necessary and it's removal has sped everything up.
=> Remove SSLCertName from fake server

lib/miniproxy/remote.rb, lib/miniproxy/server.rb, spec/integration/stub_requests_spec.rb, spec/lib/miniproxy/remote_spec.rb
This allows us to capture the output with rspec more easily, making our integration tests looking for stdout messages actually work as expected.
The messages are queued on the remote process, to be drained by the client (main process) whenever the client connects to the remote object.
=> Add message queue for remote process, drained to stdout in main

LICENSE.txt, miniproxy.gemspec
This PR aims to add a license to MiniProxy and The Conversation dev team as author to `MiniProxy`.
=> Add author and license

README.md, lib/miniproxy/config.rb, lib/miniproxy/fake_ssl_server.rb, lib/miniproxy/proxy_server.rb, lib/miniproxy/remote.rb, lib/miniproxy/server.rb, spec/integration/allow_external_requests_spec.rb
We'd like to be able to use MiniProxy for jobs and donations, but the tests of both of these apps need to be able to hit the internet, a feature MiniProxy currently doesn't provide. To fix this, add a configuration option `allow_external_requests` (off by default).
I was somewhat limited in the configuration API since any changes to config must be made via a method call on `Remote`. Retrieving and mutating a `Config` object won't work since only the initial retrieval is performed via DRb - the mutations are not and so won't have any effect. Within these constraints I'm still curious for feedback on ways to improve this interface if you can see any.
TODO:
=> Allow external requests feature

lib/miniproxy.rb, lib/miniproxy/fake_ssl_server.rb, lib/miniproxy/proxy_server.rb, lib/miniproxy/remote.rb, spec/lib/miniproxy/fake_ssl_server_spec.rb, spec/lib/miniproxy/proxy_server_spec.rb
When our specs for jobs run in docker, they run on a specific IP address, not on 127.0.0.1. Therefore, we need to allow MiniProxy to connect to this host. Add support for setting a custom host for MiniProxy, and allow requests to that host.
=> Mutable allowed hosts

README.md
- Related to #25 
This PR documents the new feature introduced at PR #25. Keep in mind that this feature is already documented at the CHANGELOG PR (#26).
=> Add `MiniProxy.host=` configuration to the README

CHANGELOG.md, lib/miniproxy/proxy_server.rb, lib/miniproxy/version.rb, spec/lib/miniproxy/proxy_server_spec.rb
This allows for things like websocket connections from clients to be negotiated successfully through the proxy.
For a great explantion of how clients negotiate websocket connections through proxy servers, take a look at this:
https://www.infoq.com/articles/Web-Sockets-Proxy-Servers
=> Allow websocket connections to pass through

.travis.yml
This PR updates MiniProxy's Firefox version, testing it against its latest version at the time of this writing (v65.0).
=> Update Travis Firefox version to 65.0

.travis.yml
This PR aims to broad MiniProxy's Ruby versions on Travis CI, making sure it works on Ruby versions from `2.4` until `2.7`.
=> Test MiniProxy against Ruby 2.4 until 2.7

.gitignore, README.md, lib/miniproxy.rb, lib/miniproxy/fake_ssl_server.rb, lib/miniproxy/proxy_server.rb, lib/miniproxy/remote.rb, lib/miniproxy/stub/request.rb, spec/integration/stub_requests_spec.rb, spec/lib/miniproxy/fake_ssl_server_spec.rb, spec/lib/miniproxy/proxy_server_spec.rb, spec/lib/miniproxy/remote_spec.rb, spec/lib/miniproxy/stub/request_spec.rb
We have a scenario where we want particular domains to be permitted through the proxy as we want a real response rather than a mock. Since MiniProxy defaults to responding with an empty 200 when an unmocked request is made, we can't do that.
This adds an 'allow_request' option that takes a method and URL pattern. When a request is made that matches an allowed request it will be permitted through the proxy.
Requests for localhost, 127.0.0.1, and whatever the MiniProxy configured host is will continue to always be permitted.
=> Support configurable allowed requests

.travis.yml
Support for Ruby 2.4 ended in April this year, so Ruby 2.4 will no longer be supported for this gem anymore either.
https://www.ruby-lang.org/en/news/2020/04/05/support-of-ruby-2-4-has-ended/
=> Drop support for Ruby 2.4

lib/miniproxy/proxy_server.rb, spec/lib/miniproxy/proxy_server_spec.rb, spec/support/server.rb
In Ruby 2.6 the signature of `perform_proxy_request` has changed; it no longer takes two arguments and a block but now three or four arguments. This means the PUT, PATCH, and DELETE extensions made to the WEBrick HTTP proxy server do not work on Ruby 2.6.
This adds test coverage for each supported HTTP method and fixes the extensions.
https://github.com/ruby/webrick/blob/4938ec3fae3ce32cceb685f6b8efff8926340c09/lib/webrick/httpproxy.rb#L302
=> Fix proxy method extensions in Ruby 2.6

lib/miniproxy/proxy_server.rb, spec/lib/miniproxy/proxy_server_spec.rb
**Why are we doing this?**
In donations, we'd like to test wallet payments (PR https://github.com/conversation/tc-donations/pull/1649), which involves sending a POST request to one of our endpoints through miniproxy. This POST request was failing with `NoMethodError`, which is interpreted by WEBrick as "POST method not implemented".
This was actually an incorrect classification; the `NoMethodError` wasn't caused by `do_POST` missing, but because of a different missing method.
In particular, webmock will attempt to call `#read` on the POST body stream:
https://github.com/bblimke/webmock/blob/master/lib/webmock/http_lib_adapters/net_http.rb#L331
By default, WEBrick will pass the `HTTPRequest` object here, which can't be read in the same way: …
=> Fix pass-through of POST requests when interacting with webmock

.github/workflows/test.yml, README.md, miniproxy.gemspec
Ruby 2.6 will be end-of-life in two weeks. Ruby 3.0 and 3.1 are out now, and we want to support them as we're migrating to 3.1.
https://endoflife.date/ruby
=> Update supported Ruby versions

lib/miniproxy/proxy_server.rb, spec/lib/miniproxy/proxy_server_spec.rb
#39 addressed a clash between webmock and miniproxy that prevented donations wallet specs from running, but was unfortunately [incompatible with TC](https://github.com/conversation/tc/pull/11735). We now have [a cleaner solution](https://github.com/conversation/tc-donations/pull/2021/files#diff-89eebfcbc0f14b6d989517837ca1e94fce4e2ce9a03233641cd936f2b8d2ed94) to prevent them from interfering with each other so we can revert this fix.
=> Revert "Provide POST body as #read -able stream"

.github/workflows/test.yml, README.md
* README: we are no longer using Travis CI to run `miniproxy` tests. We have replaced it with GitHub actions (see https://github.com/conversation/miniproxy/pull/41)
* `actions/checkout` update: version 2 has been marked as deprecated, so we're using the latest stable version, with its full semver tag reference
* Deprecation warning: https://github.com/conversation/miniproxy/actions/runs/4819829646
=> Update README and GitHub actions dependencies
